// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _MaterialAnalysis_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// closest_sample
int closest_sample(const NumericVector x, const NumericMatrix& constituent_samples);
RcppExport SEXP _MaterialAnalysis_closest_sample(SEXP xSEXP, SEXP constituent_samplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type constituent_samples(constituent_samplesSEXP);
    rcpp_result_gen = Rcpp::wrap(closest_sample(x, constituent_samples));
    return rcpp_result_gen;
END_RCPP
}
// utility
NumericVector utility(const NumericMatrix& d, const List& B);
RcppExport SEXP _MaterialAnalysis_utility(SEXP dSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const List& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(utility(d, B));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MaterialAnalysis_rcpp_hello_world", (DL_FUNC) &_MaterialAnalysis_rcpp_hello_world, 0},
    {"_MaterialAnalysis_closest_sample", (DL_FUNC) &_MaterialAnalysis_closest_sample, 2},
    {"_MaterialAnalysis_utility", (DL_FUNC) &_MaterialAnalysis_utility, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_MaterialAnalysis(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
