# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('_MaterialAnalysis_rcpp_hello_world', PACKAGE = 'MaterialAnalysis')
}

closest_sample <- function(x, constituent_samples) {
    .Call('_MaterialAnalysis_closest_sample', PACKAGE = 'MaterialAnalysis', x, constituent_samples)
}

utility <- function(d, B) {
    .Call('_MaterialAnalysis_utility', PACKAGE = 'MaterialAnalysis', d, B)
}

